baseURL = "https://hean01.github.io/"
languageCode = "en-us"
title = "Meandrous"

[taxonomies]
	category = "categories"
	tags = "tags"

[params]
	githubuser = "hean01"
	description = "nothing about everything"
	author = "Henrik Andersson"
