baseURL = "https://hean01.github.io/"
languageCode = "en-us"
title = "Meandrous"
theme = "beautifulhugo"

[Params]
	subtitle = "everything about nothing"
	logo = "img/avatar.svg"
	rss = true

[Author]
	name = "Henrik Andersson"
	email = "henrik.4e@gmail.com"
	github = "hean01"

[[menu.main]]
	identifier = "mead"
	name = "Mead recipes"
	weight = 1

[[menu.main]]
	parent = "mead"
	name = "BlueRasp Mead"
	url = "/post/Blueberry-Raspberry-mead"

[[menu.main]]
	parent = "mead"
	name = "Pineapple Coconut Mead"
	url = "/post/Pineapple-Coconut-mead"

[[menu.main]]
	parent = "mead"
	name = "JAO Mead"
	url = "/post/JAO-mead"

[[menu.main]]
	parent = "mead"
	name = "PGW show mead"
	url = "/post/PGW-mead-startkit"

[[menu.main]]
	name = "Categories"
	url = "/categories"
	weight = 2

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 3
