baseURL = "https://hean01.github.io/"
languageCode = "en-us"
title = "Meandrous"
theme = "beautifulhugo"

[Params]
	subtitle = "nothing about everything"
	logo = "img/avatar.svg"
	rss = true

[Author]
	name = "Henrik Andersson"
	email = "henrik.4e@gmail.com"
	github = "hean01"

[[menu.main]]
	name = "Categories"
	url = "/categories"
	weight = 1

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 3
